INSERT INTO movies (title, genre, rating, year) VALUES ('Challengers', 'Action', 7.5, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('The Fall Guy', 'Action', 7.3, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('Boy Kills World', 'Action', 6.7, 2023);
INSERT INTO movies (title, genre, rating, year) VALUES ('Mother of the Bride', 'Action', 4.9, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('Mothers'' Instinct', 'Action', 6.3, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('Force of Nature: The Dry 2', 'Crime', 6, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('[ES] The Courier', 'Crime', 6, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('The Last Stop in Yuma County', 'Action', 7, 2023);
INSERT INTO movies (title, genre, rating, year) VALUES ('Please Don''t Destroy: The Treasure of Foggy Mountain', 'Action', 6.1, 2023);
INSERT INTO movies (title, genre, rating, year) VALUES ('[ML] Manjummel Boys', 'Action', 8.4, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('Dune: Part Two', 'Action', 8.6, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('Turtles All the Way Down', 'Action', 6.7, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('Flynn', 'Action', 4.4, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('Unfrosted', 'Action', 5.5, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('One Bad Apple: A Hannah Swensen Mystery', 'Action', 6.5, 2024);
INSERT INTO movies (title, genre, rating, year) VALUES ('[TR] About Dry Grasses', 'Action', 7.8, 2023);
INSERT INTO movies (title, genre, rating, year) VALUES ('The Hill', 'Action', 6.7, 2023);
INSERT INTO movies (title, genre, rating, year) VALUES ('Out of Darkness', 'Horror', 5.5, 2022);
INSERT INTO movies (title, genre, rating, year) VALUES ('Stopmotion', 'Action', 5.5, 2023);
INSERT INTO movies (title, genre, rating, year) VALUES ('[ES] Through My Window: Looking at You', 'Action', 5.4, 2024);
